# Generated by Django 3.2 on 2022-01-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('excerpt', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.AlterModelOptions(
            name='trailers',
            options={'verbose_name': 'Trailer', 'verbose_name_plural': 'Trailers'},
        ),
        migrations.AddField(
            model_name='trailers',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trailers.sector'),
        ),
    ]
