# Generated by Django 3.2 on 2022-01-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trailers', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trailers',
            old_name='title',
            new_name='name',
        ),
    ]
