# Generated by Django 3.2 on 2022-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trailers', '0006_alter_trailers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailers',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
